[ Feature request] : addon of jule program for reverse the string
TheAlgorithms/Jule pull request #45
Opened 2024-10-20 09:49 UTC by Jivanjamadar

added 2 files of program based on jule programming language:
1) StringReverse.jule : contains the main logic for reversing the string
2) Stringreversetest.jule: contains necessary test cases for testing this code in jule

2024-10-20 09:50 UTC, Jivanjamadar commented
@mertcandav please review this

2024-10-20 15:46 UTC, mertcandav requested changes

2024-10-20 15:46 UTC, mertcandav commented on strings/StringReverseTest.jule
> +                t.Error("Expected: {}, got{}", test.expected, funcResult)
`testing::T` is not have the `Error` method.
It should be `Errorf`.
```suggestion
                t.Errorf("Expected: {}, got{}", test.expected, funcResult)
```

2024-10-20 15:46 UTC, mertcandav commented on strings/StringReverseTest.jule
> +        for_, test in StringReverseTests{
The `for_` is a invalid syntax. We need to separate it.
```suggestion
        for _, test in StringReverseTests {
```

2024-10-20 15:46 UTC, mertcandav commented on strings/StringReverseTest.jule
> +struc StringReverseTest {
There is no `struc` keyword, it should be `struct`.
```suggestion
struct StringReverseTest {
```

2024-10-20 15:46 UTC, mertcandav commented on strings/StringReverse.jule
This is a totally a wrong and inefficient implementation.
Jule have unicode support, so unicode characters should be handled correctly.
You are reversing string byte-by-byte. You have to reverse rune-by-rune.

2024-10-20 15:46 UTC, mertcandav commented on strings/StringReverse.jule
> +fn StringReverse(s: str): str{
This function defined in the `strings` package.
So, naming can be more simple.
```suggestion
fn Reverse(s: str): str {
```

2024-10-20 15:48 UTC, mertcandav reviewed
Please rename files:
- `StringReverse.jule` as `reverse.jule`
- `StringReverseTest.jule` as `reverse_test.jule`

2024-10-20 16:02 UTC, Jivanjamadar commented on strings/StringReverse.jule
Extremely sorry sir, Jule is very new language for me and for most of developers. I getting wrong in its syntax. I am trying my best to do that. Please, give me some time. I will try to correct it and get back to you. Thank you

2024-10-21 07:24 UTC, mertcandav commented on strings/StringReverse.jule
It's ok. You can request a review whenever you ready.
Thank you for your willingness to contribute.

2024-10-22 17:19 UTC, Jivanjamadar commented
@mertcandav I have done changes which you requested. Please review the program files of test & main logic and give your reveiw for futrue changes, Thank you!

2024-10-23 11:06 UTC, mertcandav requested changes
There are still a few issues other than the ones I mentioned. Please fix the implementation issues described, then I will merge this PR and fix the remaining issues.

2024-10-23 11:06 UTC, mertcandav commented on strings/reverse.jule
> +    for i := 0; i < len(runes); i++ {
Invalid iteration syntax.
```suggestion
    mut i := 0
    for i < len(runes); i++ {
```

2024-10-23 18:50 UTC, mertcandav approved these changes
LGTM. Thanks for your contributions.

2024-10-23 18:51 UTC, merged